### PR TITLE
mock up

### PR DESCRIPTION
**Pull request by chichaparadise**
Description:
Simple e-commerce app for selling sneakers. Users can look through offers or search for them. Authenticated users can buy sneakers by entering their payment data(no Stripe integration is intended).

Features:
- Full-text search
- Slider
- Switching sneakers colors
- Payment page
- Switching price between usd/eur or any other currency(by converting from some open api)

Data models:
- user:
  email
  name last name
  address
  mobile phone
- sneakers:
  model name
  price
  available sizes
  available colors

### CODE REVIEW

**Review by katetushkan — CHANGES_REQUESTED** [review]
Not detailed enough. One more page would also be a great addition.

**Comment by chichaparadise** [comment]
> Not detailed enough. A couple of other pages would also be a great addition.

I have auth pages and poping-up payment element
Other pages don't even fit into my idea
More details:
- full-text search - search through models on the web site. If search string satisfies some model it is displayed on slider

- slider - a collection of models which would be represented on the web site

- switching sneakers colors - click on a color and image changes

- payment page - after click on a Buy button a window for filling payment and delivery data appears

- switching price between usd and eur or any other currency - multipling assets price by k which is dollar/certain currency 

If by `not detailed enough` you've meant to add more user experience may be you can advise me something please because that design is how I see it.
image
image

**Comment by katetushkan** [comment]
> > Not detailed enough. A couple of other pages would also be a great addition.
> 
> I have auth pages and poping-up payment element Other pages don't even fit into my idea More details:
> 
> * full-text search - search through models on the web site. If search string satisfies some model it is displayed on slider
> * slider - a collection of models which would be represented on the web site
> * switching sneakers colors - click on a color and image changes
> * payment page - after click on a Buy button a window for filling payment and delivery data appears
> * switching price between usd and eur or any other currency - multipling assets price by k which is dollar/certain currency
> 
> If by `not detailed enough` you've meant to add more user experience may be you can advise me something please because that design is how I see it. image image

by `not detailed enough` I mean not enough detailed in HTML tags, u have only high level, need to go a lil bit deeper. New pages should also have tags on top.

**Comment by chichaparadise** [comment]
https://miro.com/app/board/uXjVO2NVA80=/?share_link_id=207859297702

**Review by katetushkan — CHANGES_REQUESTED** [review]
Screenshot 2022-05-12 at 12 38 08
U can't have `h2` before `h1`
Screenshot 2022-05-12 at 12 38 53
Should be `button` with `img` inside 

Screenshot 2022-05-12 at 12 39 32

Use more specific tag.
Screenshot 2022-05-12 at 12 41 03
Should be `radio button`
Screenshot 2022-05-12 at 12 41 36
U can have only one `h1` on the page.

Screenshot 2022-05-12 at 12 42 04
Should be links with `img` inside
Screenshot 2022-05-12 at 12 42 36
Same here.
Screenshot 2022-05-12 at 12 43 36
it's clickable, innit?
Screenshot 2022-05-12 at 12 44 42
`radio`

**Comment by chichaparadise** [comment]
https://miro.com/app/board/uXjVO2NVA80=/
fixed almost all moments except following:
image
does not intended to be clickable, script runs on `input` event, image here is to define the purpose of input element
image
to my mind no sense in radio buttons since this doesn't expected to be sent on a backend or smth and I don't need some sort of circles like here:
image

image
added more explicit tag in the miro template, these are just two links to switch between pages

**Review by katetushkan — CHANGES_REQUESTED** [review]
Add link to the readme as well as ur name and group.

**Review by katetushkan — APPROVED** [review]
<kbd>7</kbd>.

**Pull request merged**
